### ISSUE TITLE
feat: random radio station

### ISSUE THREAD

**Issue by kian6639** [tomassasovsky/radio-horizon.dart#32]
It could be a command prompt which you initiate, causing the robot to play a completely random radio station in the voice chat!

**Comment by tomassasovsky** [comment]
Hi @kian6639 👋
Thanks for opening an issue!

The team and I loved this suggestion, so it is now one of the following items on the roadmap, and we’re currently evaluating approaches. We’ll provide updates sometime next week 👍

**Comment by tomassasovsky** [comment]
Here's the API reference available to us to implement this feature: https://github.com/MrMirhan/Radio-Garden-API
@tomasatisocco Assigning this to you!

**Comment by tomassasovsky** [comment]
@tomasatisocco any updates on this?

**Comment by kian6639** [comment]
> @tomasatisocco any updates on this?

What?

**Comment by tomassasovsky** [comment]
@jorger5 Reassigning this to you!
